#8
#Heuristicas

import random # Importa el módulo 'random' para generar números aleatorios, que se utilizarán para crear grafos y rutas de manera aleatoria
import networkx as nx # Importa el módulo 'networkx' para trabajar con grafos, lo que facilitará la creación, manipulación y visualización de grafos en el código
import matplotlib.pyplot as plt # Importa el módulo 'matplotlib.pyplot' para crear gráficos y visualizaciones, que se utilizará para mostrar el grafo y las rutas durante la ejecución del algoritmo de heurística


def generate_complete_graph(num_nodes, weight_range=(1, 10)): # Función para generar un grafo completo con un número específico de nodos y un rango de pesos para las aristas, lo que permitirá crear grafos aleatorios para probar el algoritmo de heurística
    G = nx.complete_graph(num_nodes) # Crea un grafo completo utilizando 'networkx', donde cada nodo está conectado a todos los demás nodos, lo que es útil para probar algoritmos de heurística en grafos densos
    for (u, v) in G.edges(): #  Itera sobre todas las aristas del grafo completo, asignando un peso aleatorio a cada arista dentro del rango especificado, lo que simula diferentes costos de viaje entre los nodos en el contexto de problemas como el TSP (Traveling Salesman Problem)
        G.edges[u, v]['weight'] = random.randint(*weight_range) # Asigna un peso aleatorio a cada arista del grafo, utilizando 'random.randint' para generar un número entero dentro del rango especificado por 'weight_range', lo que permite simular diferentes costos de viaje entre los nodos en el grafo completo generado
    return G  # Retorna el grafo completo generado con pesos asignados a las aristas, lo que se utilizará para probar el algoritmo de heurística


def plot_graph_step(G, tour, current_node, pos):  # Función para visualizar el grafo y la ruta actual en cada paso del algoritmo de heurística, lo que ayuda a entender cómo se construye la solución a medida que se avanza en el proceso de búsqueda
    plt.clf() # Limpia la figura actual para preparar la visualización del siguiente paso, lo que permite mostrar la evolución de la ruta a medida que se construye durante la ejecución del algoritmo de heurística
    nx.draw(G, pos, with_labels=True, node_color='lightblue', node_size=500) # Dibuja el grafo utilizando 'networkx', mostrando los nodos con etiquetas, un color específico y un tamaño definido, lo que facilita la visualización de la estructura del grafo y la identificación de los nodos durante el proceso de construcción de la ruta en el algoritmo de heurística
    path_edges = list(zip(tour, tour[1:] + [tour[0]])) # Crea una lista de aristas que representan la ruta actual, conectando cada nodo en el tour con el siguiente nodo, y cerrando el ciclo al conectar el último nodo con el primero, lo que permite visualizar la ruta completa en el grafo durante la ejecución del algoritmo de heurística
    nx.draw_networkx_edges(G, pos, edgelist=path_edges, edge_color='red', width=2) # Dibuja las aristas que representan la ruta actual en el grafo, utilizando un color específico y un ancho definido, lo que resalta la ruta construida hasta el momento durante la ejecución del algoritmo de heurística
    nx.draw_networkx_nodes(G, pos, nodelist=[current_node], node_color='green', node_size=500) # Dibuja el nodo actual en la ruta con un color diferente para destacarlo, lo que ayuda a visualizar el progreso del algoritmo de heurística al mostrar cuál es el nodo actual que se está considerando en cada paso del proceso de construcción de la ruta

    edge_labels = nx.get_edge_attributes(G, 'weight') # Obtiene los pesos de las aristas del grafo para mostrarlos como etiquetas en la visualización, lo que proporciona información adicional sobre los costos de viaje entre los nodos en el contexto de problemas como el TSP (Traveling Salesman Problem) durante la ejecución del algoritmo de heurística
    nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels) # Dibuja las etiquetas de los pesos de las aristas en la visualización del grafo, lo que permite ver los costos asociados a cada conexión entre nodos durante la ejecución del algoritmo de heurística

    plt.pause(0.5) # Pausa la visualización durante un breve momento para permitir que el usuario vea cada paso del proceso de construcción de la ruta, lo que facilita la comprensión del algoritmo de heurística a medida que se avanza en la búsqueda de una solución aproximada al problema del TSP (Traveling Salesman Problem) en el grafo generado


def calculate_tour_cost(G, tour): # Función para calcular el costo total de un tour dado, sumando los pesos de las aristas que conectan los nodos en la ruta, lo que permite evaluar la calidad de la solución obtenida por el algoritmo de heurística en comparación con otras posibles soluciones o con el costo óptimo si se conoce, proporcionando información sobre la efectividad de la heurística utilizada para resolver problemas como el TSP (Traveling Salesman Problem) en el grafo generado.
    return sum(G.edges[tour[i], tour[i + 1]]['weight'] for i in range(len(tour) - 1)) # Función para calcular el costo total de un tour dado, sumando los pesos de las aristas que conectan los nodos en la ruta, lo que permite evaluar la calidad de la solución obtenida por el algoritmo de heurística en comparación con otras posibles soluciones o con el costo óptimo si se conoce, proporcionando información sobre la efectividad de la heurística utilizada para resolver problemas como el TSP (Traveling Salesman Problem) en el grafo generado.


def nearest_neighbor_heuristic(G, start_node=None): # Función que implementa la heurística del vecino más cercano para encontrar un tour aproximado en un grafo, lo que es útil para resolver problemas como el TSP (Traveling Salesman Problem) de manera eficiente aunque no garantice una solución óptima, y permite evaluar la calidad de la solución obtenida por esta heurística en comparación con otras posibles soluciones o con el costo óptimo si se conoce.
    if start_node is None: #    Si no se proporciona un nodo de inicio, selecciona uno aleatoriamente del grafo, lo que permite ejecutar el algoritmo de heurística del vecino más cercano desde diferentes puntos de partida para evaluar la calidad de las soluciones obtenidas en el contexto de problemas como el TSP (Traveling Salesman Problem) en el grafo generado.
        start_node = random.choice(list(G.nodes)) # Si no se proporciona un nodo de inicio, selecciona uno aleatoriamente del grafo, lo que permite ejecutar el algoritmo de heurística del vecino más cercano desde diferentes puntos de partida para evaluar la calidad de las soluciones obtenidas en el contexto de problemas como el TSP (Traveling Salesman Problem) en el grafo generado.

    pos = nx.spring_layout(G) # Calcula la posición de los nodos para la visualización utilizando el algoritmo de disposición de resorte, lo que proporciona una representación visual clara y estéticamente agradable del grafo durante la ejecución del algoritmo de heurística del vecino más cercano.
    plt.ion() # Activa el modo interactivo de Matplotlib para permitir la visualización en tiempo real del grafo y la ruta durante la ejecución del algoritmo de heurística, lo que facilita la comprensión del proceso de construcción de la solución a medida que se avanza en el algoritmo.
    plt.show() # Activa el modo interactivo de Matplotlib para permitir la visualización en tiempo real del grafo y la ruta durante la ejecución del algoritmo de heurística, lo que facilita la comprensión del proceso de construcción de la solución a medida que se avanza en el algoritmo.
 
    unvisited = set(G.nodes) # Crea un conjunto de nodos no visitados a partir de los nodos del grafo, lo que se utilizará para rastrear qué nodos aún no han sido incluidos en la ruta durante la ejecución del algoritmo de heurística del vecino más cercano.
    unvisited.remove(start_node) # Elimina el nodo de inicio del conjunto de nodos no visitados, lo que es necesario para comenzar a construir la ruta utilizando la heurística del vecino más cercano en el contexto de problemas como el TSP (Traveling Salesman Problem) en el grafo generado.
    tour = [start_node] # Inicializa la ruta con el nodo de inicio seleccionado, lo que es necesario para comenzar a construir la ruta utilizando la heurística del vecino más cercano en el contexto de problemas como el TSP (Traveling Salesman Problem) en el grafo generado.
    current_node = start_node # Inicializa el nodo actual como el nodo de inicio seleccionado, lo que es necesario para comenzar a construir la ruta utilizando la heurística del vecino más cercano en el contexto de problemas como el TSP (Traveling Salesman Problem) en el grafo generado.

    plot_graph_step(G, tour, current_node, pos) # Visualiza el estado inicial del grafo y la ruta, mostrando el nodo de inicio seleccionado y la estructura del grafo antes de comenzar a construir la ruta utilizando la heurística del vecino más cercano.

    while unvisited:    # Mientras haya nodos no visitados, continúa construyendo la ruta utilizando la heurística del vecino más cercano, lo que permite avanzar en la construcción de la solución aproximada al problema del TSP (Traveling Salesman Problem) en el grafo generado
        next_node = min(unvisited, key=lambda node: G.edges[current_node, node]['weight']) # Selecciona el siguiente nodo no visitado que tenga el peso de arista más bajo desde el nodo actual, lo que implementa la heurística del vecino más cercano para construir una ruta aproximada en problemas como el TSP (Traveling Salesman Problem) en el grafo generado.
        tour.append(next_node) # Agrega el siguiente nodo seleccionado a la ruta actual, lo que permite construir la solución aproximada al problema del TSP (Traveling Salesman Problem) utilizando la heurística del vecino más cercano en el grafo generado.
        unvisited.remove(next_node) # Elimina el nodo seleccionado de la lista de nodos no visitados, lo que asegura que el algoritmo de heurística del vecino más cercano no vuelva a considerar ese nodo en futuras iteraciones, permitiendo avanzar en la construcción del tour sin repetir nodos ya visitados.
        current_node = next_node # Actualiza el nodo actual al siguiente nodo seleccionado, lo que permite avanzar en la construcción del tour durante la ejecución del algoritmo de heurística del vecino más cercano en el contexto de problemas como el TSP (Traveling Salesman Problem) en el grafo generado.
        plot_graph_step(G, tour, current_node, pos) # Visualiza cada paso del proceso de construcción del tour, mostrando la ruta actual y el nodo que se está considerando en ese momento durante la ejecución del algoritmo de heurística

    tour.append(start_node) # Cierra el ciclo volviendo al nodo de inicio para completar el tour, lo que es necesario en problemas como el TSP (Traveling Salesman Problem) donde se busca una ruta que regrese al punto de partida después de visitar todos los nodos, y permite visualizar la ruta completa al finalizar la construcción del tour en el algoritmo de heurística del vecino más cercano.
    plot_graph_step(G, tour, current_node, pos) # Visualiza el tour completo al finalizar la construcción de la ruta, lo que permite ver la solución aproximada encontrada por la heurística del vecino más cercano en el contexto de problemas como el TSP (Traveling Salesman Problem) en el grafo generado.

    print(tour) # Imprime el tour aproximado encontrado por la heurística, lo que muestra la secuencia de nodos visitados en la ruta construida por el algoritmo de heurística para resolver el problema del TSP (Traveling Salesman Problem) en el grafo generado.
    tour_cost = calculate_tour_cost(G, tour) # Calcula el costo total del tour encontrado por la heurística, lo que permite evaluar la calidad de la solución obtenida por el algoritmo de heurística en comparación con otras posibles soluciones o con el costo óptimo si se conoce, proporcionando información sobre la efectividad de la heurística utilizada para resolver el problema del TSP (Traveling Salesman Problem) en el grafo generado.
    print(f"Tour cost: {tour_cost}")  # Imprime el costo total del tour encontrado por la heurística, lo que permite evaluar la calidad de la solución obtenida por el algoritmo de heurística en comparación con otras posibles soluciones o con el costo óptimo si se conoce, proporcionando información sobre la efectividad de la heurística utilizada para resolver el problema del TSP (Traveling Salesman Problem) en el grafo generado.

    plt.ioff() # Desactiva el modo interactivo de Matplotlib, lo que permite mantener la visualización del grafo abierta después de completar el tour, para que el usuario pueda revisar la ruta final y los costos asociados antes de cerrar la ventana de visualización del grafo.
    plt.show() # Mantiene la visualización abierta después de completar el tour, lo que permite al usuario revisar la ruta final y los costos asociados antes de cerrar la ventana de visualización del grafo.

    return tour # Retorna el tour aproximado encontrado por la heurística del vecino más cercano, lo que proporciona una solución aproximada al problema del TSP (Traveling Salesman Problem) en el grafo generado, y permite evaluar la efectividad de la heurística utilizada para resolver este tipo de problemas de optimización combinatoria.


if __name__ == "__main__": # Punto de entrada del programa, donde se genera un grafo completo, se ejecuta la heurística del vecino más cercano para encontrar un tour aproximado, se calcula el costo del tour y se muestra la ruta y su costo en la visualización del grafo.
    G = generate_complete_graph(5) # Genera un grafo completo con 5 nodos y pesos aleatorios para las aristas, lo que proporciona un entorno de prueba para el algoritmo de heurística del vecino más cercano en el contexto de problemas como el TSP (Traveling Salesman Problem)

    approx_tour = nearest_neighbor_heuristic(G, start_node=None) # Llama a la función 'nearest_neighbor_heuristic' para encontrar un tour aproximado utilizando la heurística del vecino más cercano, pasando el grafo generado y un nodo de inicio opcional (en este caso, se deja como None para seleccionar un nodo aleatorio), lo que permite obtener una solución aproximada al problema del TSP (Traveling Salesman Problem) en el grafo generado.
    approx_tour_cost = calculate_tour_cost(G, approx_tour) # Calcula el costo total del tour aproximado encontrado por la heurística, lo que permite evaluar la calidad de la solución obtenida por el algoritmo de heurística en comparación con otras posibles soluciones o con el costo óptimo si se conoce, proporcionando información sobre la efectividad de la heurística utilizada para resolver el problema del TSP (Traveling Salesman Problem) en el grafo generado.

    print(approx_tour)  # Imprime el tour aproximado encontrado por la heurística, lo que muestra la secuencia de nodos visitados en la ruta construida por el algoritmo de heurística para resolver el problema del TSP (Traveling Salesman Problem) en el grafo generado.
    print(approx_tour_cost) # Imprime el tour aproximado encontrado por la heurística y su costo total, lo que permite evaluar la calidad de la solución obtenida por el algoritmo de heurística en comparación con otras posibles soluciones o con el costo óptimo si se conoce, proporcionando información sobre la efectividad de la heurística utilizada para resolver el problema del TSP (Traveling Salesman Problem) en el grafo generado.