#3
#Deep First Search
#Busqueda en Profundidad

class Vertice: # Define la clase 'Vertice' para representar cada vértice del grafo, con atributos para almacenar su identificador, estado de visita, nivel en la búsqueda, padre en el recorrido y lista de vecinos
    def __init__(self, i):      # Inicializa un vértice con un identificador 'i', marcándolo como no visitado, con nivel -1 (indica que no ha sido asignado un nivel en la búsqueda) y sin padre (indica que no tiene un nodo padre en el recorrido)    
        self.id = i # Almacena el identificador del vértice, que puede ser un número, letra u otro tipo de dato que represente el nodo en el grafo
        self.visitado = False # Marca el vértice como no visitado inicialmente, lo que se utilizará para controlar el proceso de exploración en la búsqueda en profundidad (DFS)
        self.nivel = -1  # Inicializa el nivel del vértice en la búsqueda como -1, lo que indica que no se ha asignado un nivel específico durante el recorrido de DFS. El nivel se puede actualizar a medida que se exploran los nodos vecinos durante la búsqueda.
        self.padre = None # Inicializa el padre del vértice como None, lo que indica que no tiene un nodo padre asignado en el recorrido de DFS. El padre se puede actualizar a medida que se exploran los nodos vecinos durante la búsqueda, permitiendo rastrear el camino desde el nodo raíz hasta los nodos visitados.
        self.vecinos = []      # Inicializa la lista de vecinos del vértice como una lista vacía, lo que se utilizará para almacenar los nodos adyacentes a este vértice en el grafo. Los vecinos se agregarán a esta lista a medida que se construya el grafo y se definan las aristas entre los vértices.     

    def agregarVecino(self, v):    # Método para agregar un vecino a la lista de vecinos del vértice. Toma como parámetro 'v', que representa el identificador del vecino a agregar. Si el vecino no está ya en la lista de vecinos, se agrega a la lista. Esto permite construir la estructura del grafo al definir las conexiones entre los vértices mediante aristas.
        if v not in self.vecinos: # Verifica si el vecino 'v' ya está en la lista de vecinos del vértice. Si no está presente, se agrega a la lista de vecinos. Esto asegura que cada vecino se agregue solo una vez, evitando duplicados en la lista de vecinos del vértice.
            self.vecinos.append(v)  # Agrega el vecino 'v' a la lista de vecinos del vértice, estableciendo una conexión entre este vértice y el vecino en el grafo. Esto es fundamental para construir la estructura del grafo y permitir la exploración de los nodos adyacentes durante la búsqueda en profundidad (DFS).


class Grafica: # Define la clase 'Grafica' para representar el grafo completo, con métodos para agregar vértices, agregar aristas y realizar la búsqueda en profundidad (DFS)
    def __init__(self):       # Inicializa la gráfica con un diccionario vacío llamado 'vertices', donde cada clave es el identificador de un vértice y su valor es una instancia de la clase 'Vertice'. Este diccionario se utilizará para almacenar todos los vértices del grafo y sus conexiones, permitiendo construir la estructura del grafo y realizar operaciones como agregar vértices, agregar aristas y realizar la búsqueda en profundidad (DFS).    
        self.vertices = {}          # Diccionario para almacenar los vértices del grafo, donde cada clave es el identificador de un vértice y su valor es una instancia de la clase 'Vertice'. Este diccionario se utiliza para construir la estructura del grafo y realizar operaciones como agregar vértices, agregar aristas y realizar la búsqueda en profundidad (DFS).

    def agregarVertice(self, v): # Método para agregar un vértice al grafo. Toma como parámetro 'v', que representa el identificador del vértice a agregar. Si el vértice no está ya presente en el diccionario de vértices, se crea una nueva instancia de la clase 'Vertice' con el identificador 'v' y se agrega al diccionario de vértices. Esto permite construir la estructura del grafo al definir los nodos que lo componen.
        if v not in self.vertices: # Verifica si el vértice 'v' ya está presente en el diccionario de vértices del grafo. Si no está presente, se crea una nueva instancia de la clase 'Vertice' con el identificador 'v' y se agrega al diccionario de vértices. Esto asegura que cada vértice se agregue solo una vez, evitando duplicados en el diccionario de vértices del grafo.
            self.vertices[v] = Vertice(v) # Crea una nueva instancia de la clase 'Vertice' con el identificador 'v' y la agrega al diccionario de vértices del grafo, estableciendo así la presencia de este vértice en la estructura del grafo. Esto es fundamental para construir el grafo y permitir la exploración de los nodos durante la búsqueda en profundidad (DFS).

    def agregarArista(self, a, b):
        if a in self.vertices and b in self.vertices: # Método para agregar una arista entre dos vértices en el grafo. Toma como parámetros 'a' y 'b', que representan los identificadores de los vértices entre los cuales se desea agregar la arista. Verifica si ambos vértices están presentes en el diccionario de vértices del grafo. Si ambos vértices existen, se agrega 'b' como vecino de 'a' y 'a' como vecino de 'b', estableciendo así una conexión bidireccional entre los dos vértices en el grafo. Esto es fundamental para construir la estructura del grafo y permitir la exploración de los nodos adyacentes durante la búsqueda en profundidad (DFS).
            self.vertices[a].agregarVecino(b) # Agrega 'b' como vecino de 'a' en el grafo, estableciendo una conexión desde el vértice 'a' hacia el vértice 'b'. Esto es fundamental para construir la estructura del grafo y permitir la exploración de los nodos adyacentes durante la búsqueda en profundidad (DFS).
            self.vertices[b].agregarVecino(a) # Agrega 'a' como vecino de 'b' en el grafo, estableciendo una conexión desde el vértice 'b' hacia el vértice 'a'. Esto es fundamental para construir la estructura del grafo y permitir la exploración de los nodos adyacentes durante la búsqueda en profundidad (DFS).

    def DFS(self, r):  # Método para realizar la búsqueda en profundidad (DFS) a partir de un vértice raíz 'r'. Toma como parámetro 'r', que representa el identificador del vértice desde el cual se iniciará la búsqueda. Verifica si el vértice 'r' está presente en el diccionario de vértices del grafo. Si el vértice existe, se marca como visitado y se recorre su lista de vecinos. Para cada vecino, si no ha sido visitado, se establece el padre del vecino como 'r', se imprime la conexión entre el vecino y 'r', y se llama recursivamente al método DFS para continuar la exploración desde ese vecino. Esto permite realizar una búsqueda en profundidad a través del grafo, explorando todos los nodos adyacentes antes de retroceder y explorar otros caminos.
        if r in self.vertices:  # Verifica si el vértice 'r' está presente en el diccionario de vértices del grafo. Si el vértice existe, se procede con la búsqueda en profundidad (DFS) a partir de ese vértice.
            self.vertices[r].visitado = True  # Marca el vértice 'r' como visitado, lo que indica que se ha explorado este nodo durante la búsqueda en profundidad (DFS). Esto es fundamental para evitar ciclos y asegurar que cada nodo se visite solo una vez durante el recorrido del grafo.
            for nodo in self.vertices[r].vecinos:  # Recorre la lista de vecinos del vértice 'r'. Para cada vecino, se verifica si ha sido visitado. Si el vecino no ha sido visitado, se establece el padre del vecino como 'r', se imprime la conexión entre el vecino y 'r', y se llama recursivamente al método DFS para continuar la exploración desde ese vecino. Esto permite realizar una búsqueda en profundidad a través del grafo, explorando todos los nodos adyacentes antes de retroceder y explorar otros caminos.
                if self.vertices[nodo].visitado == False:  # Verifica si el vecino 'nodo' no ha sido visitado. Si el vecino no ha sido visitado, se procede a establecer su padre, imprimir la conexión y llamar recursivamente al método DFS para continuar la exploración desde ese vecino.
                    self.vertices[nodo].padre = r  # Establece el padre del vecino 'nodo' como 'r', lo que indica que 'r' es el nodo desde el cual se llegó a 'nodo' durante la búsqueda en profundidad (DFS). Esto es fundamental para rastrear el camino desde el nodo raíz hasta los nodos visitados y permite reconstruir la ruta de exploración en el grafo.
                    print("(" + str(nodo) + "," + str(r) + ")")  # Imprime la conexión entre el vecino 'nodo' y el vértice 'r', mostrando la relación entre estos dos nodos en el grafo durante la búsqueda en profundidad (DFS). Esto proporciona información sobre cómo se están explorando los nodos adyacentes durante el recorrido del grafo.
                    self.DFS(nodo)  # Llama recursivamente al método DFS para continuar la exploración desde el vecino 'nodo'. Esto permite realizar una búsqueda en profundidad a través del grafo, explorando todos los nodos adyacentes antes de retroceder y explorar otros caminos. La recursión es fundamental para implementar la lógica de la búsqueda en profundidad (DFS) y permite explorar completamente el grafo a partir del vértice raíz 'r'.


def main(): # Función principal para crear un grafo, agregar vértices y aristas, y realizar la búsqueda en profundidad (DFS) a partir de un vértice raíz. En este ejemplo, se crea un grafo con los vértices "A", "B", "C", "D" y "E", y se agregan aristas entre ellos para establecer conexiones. Luego, se llama al método DFS para iniciar la búsqueda en profundidad desde el vértice "A", lo que permite explorar el grafo y mostrar las conexiones entre los nodos durante el recorrido.
    g = Grafica()  # Crea una instancia de la clase 'Grafica' para representar el grafo que se va a construir y explorar. Esta instancia se utilizará para agregar vértices, agregar aristas y realizar la búsqueda en profundidad (DFS) en el grafo.
    g.agregarVertice("A")  # Agrega el vértice "A" al grafo utilizando el método 'agregarVertice' de la clase 'Grafica'. Esto establece la presencia del vértice "A" en la estructura del grafo, lo que permitirá establecer conexiones con otros vértices y realizar la búsqueda en profundidad (DFS) a partir de este vértice raíz.   
    g.agregarVertice("B")   # Agrega el vértice "B" al grafo utilizando el método 'agregarVertice' de la clase 'Grafica'. Esto establece la presencia del vértice "B" en la estructura del grafo, lo que permitirá establecer conexiones con otros vértices y realizar la búsqueda en profundidad (DFS) a partir de este vértice raíz.
    g.agregarVertice("C")   # Agrega el vértice "C" al grafo utilizando el método 'agregarVertice' de la clase 'Grafica'. Esto establece la presencia del vértice "C" en la estructura del grafo, lo que permitirá establecer conexiones con otros vértices y realizar la búsqueda en profundidad (DFS) a partir de este vértice raíz.
    g.agregarVertice("D")   # Agrega el vértice "D" al grafo utilizando el método 'agregarVertice' de la clase 'Grafica'. Esto establece la presencia del vértice "D" en la estructura del grafo, lo que permitirá establecer conexiones con otros vértices y realizar la búsqueda en profundidad (DFS) a partir de este vértice raíz.
    g.agregarVertice("E")   # Agrega el vértice "E" al grafo utilizando el método 'agregarVertice' de la clase 'Grafica'. Esto establece la presencia del vértice "E" en la estructura del grafo, lo que permitirá establecer conexiones con otros vértices y realizar la búsqueda en profundidad (DFS) a partir de este vértice raíz.
    g.agregarArista("A", "B")  # Agrega una arista entre los vértices "A" y "B" utilizando el método 'agregarArista' de la clase 'Grafica'. Esto establece una conexión bidireccional entre los vértices "A" y "B" en el grafo, lo que permitirá explorar ambos nodos durante la búsqueda en profundidad (DFS) a partir del vértice raíz "A".
    g.agregarArista("A", "C")  # Agrega una arista entre los vértices "A" y "C" utilizando el método 'agregarArista' de la clase 'Grafica'. Esto establece una conexión bidireccional entre los vértices "A" y "C" en el grafo, lo que permitirá explorar ambos nodos durante la búsqueda en profundidad (DFS) a partir del vértice raíz "A".
    g.agregarArista("B", "D")  # Agrega una arista entre los vértices "B" y "D" utilizando el método 'agregarArista' de la clase 'Grafica'. Esto establece una conexión bidireccional entre los vértices "B" y "D" en el grafo, lo que permitirá explorar ambos nodos durante la búsqueda en profundidad (DFS) a partir del vértice raíz "A".
    g.agregarArista("C", "D")  # Agrega una arista entre los vértices "C" y "D" utilizando el método 'agregarArista' de la clase 'Grafica'. Esto establece una conexión bidireccional entre los vértices "C" y "D" en el grafo, lo que permitirá explorar ambos nodos durante la búsqueda en profundidad (DFS) a partir del vértice raíz "A".
    g.agregarArista("C", "E")  # Agrega una arista entre los vértices "C" y "E" utilizando el método 'agregarArista' de la clase 'Grafica'. Esto establece una conexión bidireccional entre los vértices "C" y "E" en el grafo, lo que permitirá explorar ambos nodos durante la búsqueda en profundidad (DFS) a partir del vértice raíz "A".

    print("DFS:")   # Imprime el título "DFS:" para indicar que se va a mostrar el resultado de la búsqueda en profundidad (DFS) en el grafo. Esto proporciona contexto al usuario sobre la información que se va a presentar a continuación, que son las conexiones entre los nodos explorados durante la búsqueda en profundidad (DFS).
    g.DFS("A")  # Llama al método 'DFS' de la clase 'Grafica' para iniciar la búsqueda en profundidad (DFS) a partir del vértice raíz "A". Esto permite explorar el grafo y mostrar las conexiones entre los nodos durante el recorrido de DFS, comenzando desde el vértice "A" y explorando todos los nodos adyacentes antes de retroceder y explorar otros caminos en el grafo.


if __name__ == "__main__":  # Verifica si el script se está ejecutando como programa principal. Si es así, se llama a la función 'main()' para iniciar la ejecución del programa. Esto es una práctica común en Python para permitir que el código se ejecute solo cuando se ejecuta directamente, y no cuando se importa como módulo en otro script.
    main()      #   Llama a la función 'main()' para iniciar la ejecución del programa. Esto es fundamental para ejecutar el código que crea el grafo, agrega vértices y aristas, y realiza la búsqueda en profundidad (DFS) a partir de un vértice raíz, mostrando las conexiones entre los nodos durante el recorrido de DFS.   
